# set base image (host OS)
FROM python:3.11

# set the working directory in the container
WORKDIR /code

# copy the content of the local src directory to the working directory
COPY ./ .

# install dependencies
RUN pip install -r requirements.txt

ADD cert.crt /usr/local/share/ca-certificates/cockroachdb.cert
RUN chmod 644 /usr/local/share/ca-certificates/cockroachdb.cert && update-ca-certificates

ADD cert.crt /root/.postgresql/root.crt

# command to run on container start
#ENV DATABASE_URL postgresql://acadia:nokK7GX2HDePJwSXocspeQ@acadia-uni-4762.g8z.cockroachlabs.cloud:26257/acadia?sslmode=verify-full
ENV DATABASE_URL postgresql://acadia:nokK7GX2HDePJwSXocspeQ@127.0.0.1:7500/acadia
CMD [ "python", "./main.py" ]